from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "ENGINEERING_OVERVIEW.md"


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def parse_requirements(path: Path) -> dict[str, list[tuple[str, str]]]:
    categories: dict[str, list[tuple[str, str]]] = {}
    current = "Other"
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("#"):
            current = line.lstrip("#").strip()
            categories.setdefault(current, [])
            continue
        name, version = split_requirement(line)
        categories.setdefault(current, []).append((name, version))
    return categories


def split_requirement(line: str) -> tuple[str, str]:
    match = re.match(r"([A-Za-z0-9_.\-\[\]]+)\s*([<>=!~].+)?", line)
    if not match:
        return line, ""
    return match.group(1), (match.group(2) or "").strip()


def parse_services(compose_text: str) -> list[str]:
    services: list[str] = []
    in_services = False
    for line in compose_text.splitlines():
        if line.startswith("services:"):
            in_services = True
            continue
        if in_services:
            if re.match(r"^[A-Za-z0-9_]+:", line):
                break
            match = re.match(r"^  ([a-zA-Z0-9_-]+):\s*$", line)
            if match:
                services.append(match.group(1))
    return services


def top_level_tree() -> list[str]:
    items: list[str] = []
    for path in sorted(ROOT.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower())):
        if path.name in {".git", ".next", "node_modules", "__pycache__"}:
            continue
        suffix = "/" if path.is_dir() else ""
        items.append(f"- `{path.name}{suffix}`")
    return items


def app_tree(base: Path, depth: int = 2) -> list[str]:
    lines: list[str] = []

    def walk(path: Path, level: int) -> None:
        if level > depth:
            return
        for child in sorted(path.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower())):
            if child.name in {"__pycache__", ".next", "node_modules"}:
                continue
            indent = "  " * level
            suffix = "/" if child.is_dir() else ""
            rel = child.relative_to(ROOT).as_posix()
            lines.append(f"{indent}- `{rel}{suffix}`")
            if child.is_dir():
                walk(child, level + 1)

    walk(base, 0)
    return lines


def router_inventory(router_dir: Path) -> list[str]:
    routers = []
    for path in sorted(router_dir.glob("*.py")):
        if path.name == "__init__.py":
            continue
        routers.append(path.stem)
    return routers


def count_tests(test_dir: Path) -> tuple[int, list[tuple[str, int]]]:
    total = 0
    files: list[tuple[str, int]] = []
    for path in sorted(test_dir.glob("test_*.py")):
        content = path.read_text(encoding="utf-8")
        count = len(re.findall(r"^def test_|^async def test_", content, flags=re.MULTILINE))
        total += count
        files.append((path.name, count))
    return total, files


def workflow_names(workflows_dir: Path) -> list[str]:
    return [path.name for path in sorted(workflows_dir.glob("*.yml"))]


def build_doc() -> str:
    package = read_json(ROOT / "apps" / "web" / "package.json")
    requirements = parse_requirements(ROOT / "services" / "api" / "requirements.txt")
    compose_text = (ROOT / "docker-compose.dev.yml").read_text(encoding="utf-8")
    services = parse_services(compose_text)
    routers = router_inventory(ROOT / "services" / "api" / "app" / "routers")
    total_tests, test_files = count_tests(ROOT / "services" / "api" / "tests")
    workflows = workflow_names(ROOT / ".github" / "workflows")

    backend_core = requirements.get("Web framework", []) + requirements.get("Database", [])
    backend_llm = requirements.get("LLM", [])
    backend_processing = requirements.get("Document processing", [])

    lines = [
        "# Engineering Overview",
        "",
        "This file is generated by `python scripts/generate_docs.py`.",
        "Do not edit it manually.",
        "",
        "## Project Summary",
        "",
        "TP AI is a monorepo for an AI-assisted workflow that prepares technical proposals from tender documents, examples, schedules and legislation.",
        "",
        "## Runtime Stack",
        "",
        "### Frontend",
        "",
    ]

    for dep in ("next", "react", "react-dom"):
        lines.append(f"- `{dep}`: `{package['dependencies'][dep]}`")

    lines.extend([
        "",
        "### Backend",
        "",
    ])
    for name, version in backend_core:
        lines.append(f"- `{name}`: `{version}`")

    lines.extend([
        "",
        "### LLM and Retrieval",
        "",
    ])
    for name, version in backend_llm:
        lines.append(f"- `{name}`: `{version}`")
    for name, version in requirements.get("Redis / queue", []):
        lines.append(f"- `{name}`: `{version}`")
    for name, version in requirements.get("MinIO (S3-compatible)", []):
        lines.append(f"- `{name}`: `{version}`")
    for name, version in requirements.get("Rate limiting", []):
        lines.append(f"- `{name}`: `{version}`")

    lines.extend([
        "",
        "### Document Processing",
        "",
    ])
    for name, version in backend_processing + requirements.get("Schedule parsing вЂ” .mpp support via Java/MPXJ (requires JRE in container)", []):
        lines.append(f"- `{name}`: `{version}`")

    lines.extend([
        "",
        "## Docker Services",
        "",
    ])
    for service in services:
        lines.append(f"- `{service}`")

    lines.extend([
        "",
        "## Repository Layout",
        "",
    ])
    lines.extend(top_level_tree())

    lines.extend([
        "",
        "### Key Application Paths",
        "",
    ])
    lines.extend(app_tree(ROOT / "apps" / "web" / "src", depth=2))
    lines.extend(app_tree(ROOT / "services" / "api" / "app", depth=2))

    lines.extend([
        "",
        "## Backend API Surface",
        "",
    ])
    for router in routers:
        lines.append(f"- `services/api/app/routers/{router}.py`")

    lines.extend([
        "",
        "## Test Inventory",
        "",
        f"- Total backend tests discovered: `{total_tests}`",
    ])
    for name, count in test_files:
        lines.append(f"- `{name}`: `{count}`")

    lines.extend([
        "",
        "## Automation",
        "",
        "- Local hooks: `.githooks/pre-commit`, `.githooks/pre-push`",
        "- Generator: `scripts/generate_docs.py`",
        "- GitHub workflows:",
    ])
    for name in workflows:
        lines.append(f"- `{name}`")

    lines.extend([
        "",
        "## Notes",
        "",
        "- Product specification is maintained separately in `docs/TP_AI_Agent_Prompt_Architecture_v1.3.docx`.",
        "- `README.md` is intentionally kept short and stable; exact repo facts live here.",
        "",
    ])

    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(build_doc(), encoding="utf-8")


if __name__ == "__main__":
    main()
